[build]
builder = "RAILPACK"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "node .output/server/index.mjs"
healthcheckPath = "/"
healthcheckTimeout = 100
