import { LANDING_TAILWIND_LIMIT_KT, RCAM_LDG, RCAM_TO, TAKEOFF_TAILWIND_LIMIT_KT, WIND_DIRECTION_STEP_DEG, MATRIX_WINDOW_RADIUS_ROWS, DISPLAY_WIND_CAP_KT, PROXIMITY_THRESHOLD, type RCAM_KEYS } from '@/constants'
import { normalizeDeg, degToRad, calculateRunwayWindComponents } from './windAngles'
export type { RunwayWindComponents } from './windAngles'
export type TowerWindPhase = 'takeoff' | 'landing'; export type LimitingComponent = 'XW' | 'TW'; export type ComponentStatus = 'safe' | 'warning' | 'unsafe' | 'info'
export interface TowerWindMatrixInput { phase: TowerWindPhase; rcamCode: RCAM_KEYS; runwayHeading: number; referenceWindDirection: number }
export interface TowerWindMatrixRow { windDirection: number; maxWindKt: number | null; displayMaxWind: string; limitingComponent: LimitingComponent; isReference: boolean }
export interface TowerWindMatrix { crosswindLimitKt: number; tailwindLimitKt: number; allRows: TowerWindMatrixRow[]; visibleRows: TowerWindMatrixRow[] }
export interface CurrentWindComponentReadoutInput { runwayHeading: number; windDirection: number; windSpeed: number; phase: TowerWindPhase; rcamCode: RCAM_KEYS }
export interface CurrentWindComponentReadout { crosswind: { valueKt: number; limitKt: number; status: ComponentStatus }; longitudinal: { type: 'HW' | 'TW'; valueKt: number; limitKt: number | null; status: ComponentStatus } }
function getCrosswindLimit(p: TowerWindPhase, c: RCAM_KEYS) { return p === 'takeoff' ? RCAM_TO[c] : RCAM_LDG[c] }
function getTailwindLimit(p: TowerWindPhase) { return p === 'takeoff' ? TAKEOFF_TAILWIND_LIMIT_KT : LANDING_TAILWIND_LIMIT_KT }
function nearest(d: number) { return normalizeDeg(Math.round(normalizeDeg(d) / WIND_DIRECTION_STEP_DEG) * WIND_DIRECTION_STEP_DEG) }
function status(v: number, l: number): ComponentStatus { return v > l ? 'unsafe' : v >= l * PROXIMITY_THRESHOLD ? 'warning' : 'safe' }
export { calculateRunwayWindComponents }
export function getCurrentWindComponentReadout(input: CurrentWindComponentReadoutInput): CurrentWindComponentReadout { const x = getCrosswindLimit(input.phase, input.rcamCode); const t = getTailwindLimit(input.phase); const c = calculateRunwayWindComponents(input); return { crosswind: { valueKt: Math.round(c.crosswindKt), limitKt: x, status: status(c.crosswindKt, x) }, longitudinal: { type: c.longitudinalType, valueKt: Math.round(c.longitudinalKt), limitKt: c.longitudinalType === 'TW' ? t : null, status: c.longitudinalType === 'TW' ? status(c.longitudinalKt, t) : 'info' } } }
function maxWind(d: number, runway: number, x: number, t: number) { const r = degToRad(normalizeDeg(d - runway)); const xf = Math.abs(Math.sin(r)); const tf = Math.max(-Math.cos(r), 0); const xm = xf > 0.0001 ? x / xf : Infinity; const tm = tf > 0.0001 ? t / tf : Infinity; const limitingComponent = tm < xm ? 'TW' as const : 'XW' as const; const raw = Math.min(xm, tm); if (!Number.isFinite(raw) || raw > DISPLAY_WIND_CAP_KT) return { maxWindKt: null, displayMaxWind: `>${DISPLAY_WIND_CAP_KT} kt`, limitingComponent }; const maxWindKt = Math.round(raw); return { maxWindKt, displayMaxWind: `${maxWindKt} kt`, limitingComponent } }
export function buildTowerWindMatrix(input: TowerWindMatrixInput): TowerWindMatrix { const x = getCrosswindLimit(input.phase, input.rcamCode); const t = getTailwindLimit(input.phase); const ref = nearest(input.referenceWindDirection); const allRows = Array.from({ length: 36 }, (_, i) => { const windDirection = i * WIND_DIRECTION_STEP_DEG; return { windDirection, isReference: windDirection === ref, ...maxWind(windDirection, input.runwayHeading, x, t) } }); const visibleRows = Array.from({ length: MATRIX_WINDOW_RADIUS_ROWS * 2 + 1 }, (_, i) => allRows.find(r => r.windDirection === normalizeDeg(ref + (i - MATRIX_WINDOW_RADIUS_ROWS) * WIND_DIRECTION_STEP_DEG))).filter((r): r is TowerWindMatrixRow => !!r); return { crosswindLimitKt: x, tailwindLimitKt: t, allRows, visibleRows } }
