export const DEFAULT_MAX_TAXI_SPEED_KT = 5
export const MAX_TAXI_SPEED_INPUT_KT = 20
export const WIND_SPEED_INPUT_MAX_KT = 999

export const FRESHNESS_REFRESH_INTERVAL_MS = 60_000
export const CONDITIONS_REFRESH_INTERVAL_MS = 300_000
